name: Deploy Docs

on:
  push:
    branches:
      - main
      - feat-GCal
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Use a more recent version of checkout

      - name: Set up Python
        uses: actions/setup-python@v4 # Use a more recent version of setup-python
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build

      - name: Copy static files 1
        run: cp docs/google-auth-callback.html site/

      - name: Copy static files 2
        run: cp docs/google5612e1450dc0c1ac.html site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true # Creates a clean history for the gh-pages branch
